# Configurações da Janela
WIDTH, HEIGHT = 600, 900

# Configurações do Player
PLAYER_SPEED = 300
PLAYER_DASH_SPEED = 2000
PLAYER_RETURN_SPEED = 3000
PLAYER_START_X = WIDTH // 3
XP_BASE = 100
FACTOR = 1.5

# Configurações dos Morcegos
BAT_SPEED = 150
BAT_VERTICAL_SPEED = 150
BAT_OSCILLATION_SPEED = 50
BAT_OSCILLATION_FREQUENCY = 0.01
BAT_HITS_TO_DIE = 1
MAX_BATS = 8
MIN_SPAWN_DELAY = 1.0
MAX_SPAWN_DELAY = 2.0

# Configurações de Animação
BAT_FLY_ANIMATION_DURATION = 300
BAT_HURT_ANIMATION_DURATION = 100
BAT_DIE_ANIMATION_DURATION = 100
PLAYER_IDLE_ANIMATION_DURATION = 400
PLAYER_ATTACK_ANIMATION_DURATION = 100
BAT_XP = 10.0